Revert "Fix beta deploy regex"
This reverts commit 8580891a229f0f2e4915e382785d0f0b3433b3b7.

diff --git a/scripts/publish-beta b/scripts/publish-beta
--- a/scripts/publish-beta
+++ b/scripts/publish-beta
@@ -6,10 +6,10 @@ if [ -z "$1" ]; then
 fi
 
 pkg_name="@poap-xyz/poap-sdk"
-pkg_version="$1"
+pkg_version=$(echo "$1" | cut -d '@' -f2)
 
-if [[ ! $pkg_version =~ ^v[0-9]+\.[0-9]+\.[0-9]+-beta-[0-9]+$ ]]; then
-  echo "Error: Please provide a package BETA version ($pkg_version given)" 1>&2
+if [[ "$pkg_version" != *beta* ]]; then
+  echo "Error: Please provide a package BETA version" 1>&2
   exit 1
 fi
 
